# Github Actions 下载脚本配置

version: '2.0'

dir_rule:
  base_dir: /home/runner/work/jmcomic/download/
  rule: Bd_Aauthor_Atitle_Pindex

client:
  postman:
    meta_data:
      headers:
        referer: https://18comic.vip/
