# GitHub Actions 测试用
# 移动端配置

client:
  impl: api
  retry_times: 3
  postman:
    meta_data:
      timeout: 5

# 插件配置
plugin:
  after_init:
    - plugin: usage_log # 实时打印硬件占用率的插件
      kwargs:
        interval: 0.5 # 间隔时间
        enable_warning: false # 不告警

    - plugin: client_proxy
      kwargs:
        proxy_client_key: cl_proxy_future
        whitelist: [ api, ]