# GitHub Actions 下载脚本配置
version: '2.0'

dir_rule:
  base_dir: ${JM_DOWNLOAD_DIR}
  rule: Bd_Aauthor_Atitle_Pindex


client:
  domain:
    - jmcomic1.me
    - jmcomic.me

# 插件配置
plugin:
  after_init:
    - plugin: usage_log # 实时打印硬件占用率的插件
      kwargs:
        interval: 0.5 # 间隔时间
        enable_warning: false # 不告警


  after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        level: album # 按照章节，一个章节一个压缩文件
        filename_rule: Atitle # 压缩文件的命名规则
        zip_dir: /home/runner/work/jmcomic/zip/ # 压缩文件存放的文件夹
